meteor:
  spawn-interval: 10
  world: world
  height: 150
  speed: 0.3
  explosion-power: 4.0
  crater-radius: 5
  regeneration-time: 10
  fire-spread: true
  obsidian-sphere-radius: 3
  min-player-distance: 50
  max-player-distance: 150
  notification-radius: 200